

#ifndef Report_H_INCLUDED
#define Report_H_INCLUDED

#define REPORT_ERROR_USER_FILE_OPEN 0x00001a;
#define REPORT_ERROR_USER_FILE_DELETE 0x00001b;
#define REPORT_ERROR_USER_IO_SCAN 0x00001c;

#define DONE -1;

#define REPORT_ACTIVE_TRUE 1;
#define REPORT_ACTIVE_FALSE 0;
#define REPORT_ACTIVE_FUNCTION_END -1;



#endif